export type BuilderTemplate = {
  id: string;
  name: string;
  description: string;
  category: string;
  subcategory: string;
  nodes: { type: string; label: string; position: { x: number; y: number }; config?: Record<string, unknown> }[];
  edges: { from: number; to: number; sourceHandle?: string }[];
  docs: {
    overview: string;
    steps: string[];
    connections: string[];
    prerequisites: string[];
    similar: string[];
  };
};

const T = (t: BuilderTemplate) => t;

// ─── IT OPS ─────────────────────────────────────────────────────────────
const itOps: BuilderTemplate[] = [
  T({
    id: "it-incident-response",
    name: "IT Incident Auto-Response",
    description: "Webhook receives alerts, AI triages severity, creates tickets, notifies on-call team via Slack, and logs to database",
    category: "IT Ops",
    subcategory: "Incident Response",
    nodes: [
      { type: "trigger", label: "Alert Webhook", position: { x: 300, y: 0 } },
      { type: "ai", label: "AI Triage", position: { x: 300, y: 140 } },
      { type: "condition", label: "Is Critical?", position: { x: 300, y: 280 } },
      { type: "http", label: "Create Jira Ticket", position: { x: 150, y: 420 } },
      { type: "slack", label: "Slack Alert", position: { x: 150, y: 560 } },
      { type: "email", label: "Email Report", position: { x: 450, y: 420 } },
      { type: "database", label: "Log Incident", position: { x: 300, y: 700 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3, sourceHandle: "true" },
      { from: 2, to: 5, sourceHandle: "false" },
      { from: 3, to: 4 },
      { from: 4, to: 6 },
      { from: 5, to: 6 },
    ],
    docs: {
      overview: "Automatically receives infrastructure alerts via webhook, uses AI to triage severity, creates Jira tickets for critical issues, sends Slack notifications to on-call teams, emails non-critical reports, and logs everything to a database for audit.",
      steps: [
        "Configure alert sources (Datadog, PagerDuty, etc.) to POST to this workflow's webhook",
        "AI triages the alert payload to determine severity (critical vs non-critical)",
        "Critical alerts create a Jira ticket and send a Slack notification to the on-call channel",
        "Non-critical alerts are emailed as reports to the ops team",
        "All incidents are logged to the database for compliance and reporting",
      ],
      connections: [
        "Webhook URL from monitoring tools (Datadog, PagerDuty, CloudWatch)",
        "Jira API token for ticket creation",
        "Slack workspace webhook for notifications",
        "SMTP credentials for email reports",
        "PostgreSQL/MySQL database connection",
      ],
      prerequisites: [
        "Jira API access with ticket creation permissions",
        "Slack bot token with channel posting rights",
        "SMTP server or email service (SendGrid, SES)",
      ],
      similar: ["it-db-failure-recovery", "it-ssl-cert-alert"],
    },
  }),
  T({
    id: "it-db-failure-recovery",
    name: "Database Failure Recovery",
    description: "Detects DB downtime, pages DBA, retries with backoff, and marks healthy on recovery",
    category: "IT Ops",
    subcategory: "Infrastructure Monitoring",
    nodes: [
      { type: "trigger", label: "DB Health Alert", position: { x: 300, y: 0 } },
      { type: "condition", label: "Is Down?", position: { x: 300, y: 140 } },
      { type: "database", label: "Create Incident", position: { x: 150, y: 280 } },
      { type: "slack", label: "Page DBA", position: { x: 150, y: 420 } },
      { type: "error", label: "Retry Guard", position: { x: 300, y: 420 } },
      { type: "set", label: "Mark Healthy", position: { x: 450, y: 280 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2, sourceHandle: "true" },
      { from: 1, to: 5, sourceHandle: "false" },
      { from: 2, to: 3 },
      { from: 3, to: 4 },
    ],
    docs: {
      overview: "Monitors database health via webhook alerts. When a DB failure is detected, creates an incident record, pages the on-call DBA via Slack, and implements retry logic with exponential backoff. Automatically marks the DB as healthy when it recovers.",
      steps: [
        "Database monitoring tool sends health status to webhook",
        "Condition node checks if status is 'down'",
        "If down: creates incident in database and pages DBA via Slack",
        "Error handler implements retry with 60s delay, max 5 retries",
        "If healthy: marks the incident as resolved",
      ],
      connections: [
        "Database monitoring tool (pg_stat, custom health check)",
        "Slack channel for DBA on-call",
        "Incident management database table",
      ],
      prerequisites: [
        "Database with health check endpoint",
        "Slack workspace access",
        "Incident management table schema",
      ],
      similar: ["it-incident-response", "it-ssl-cert-alert"],
    },
  }),
  T({
    id: "it-ssl-cert-alert",
    name: "SSL Certificate Expiry Alert",
    description: "Daily cron checks cert expiry and warns before it lapses via email and Slack",
    category: "IT Ops",
    subcategory: "Security Monitoring",
    nodes: [
      { type: "trigger", label: "Daily Check", position: { x: 300, y: 0 }, config: { triggerType: "cron", cronExpression: "0 9 * * *" } },
      { type: "http", label: "Check Cert", position: { x: 300, y: 140 } },
      { type: "condition", label: "Expiring Soon?", position: { x: 300, y: 280 } },
      { type: "email", label: "Email DevOps", position: { x: 150, y: 420 } },
      { type: "slack", label: "Slack Warning", position: { x: 150, y: 560 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3, sourceHandle: "true" },
      { from: 3, to: 4 },
    ],
    docs: {
      overview: "Runs daily via cron to check SSL certificate expiry dates. When a certificate is within 14 days of expiry, sends email alerts to DevOps and posts warnings to Slack.",
      steps: [
        "Cron trigger fires daily at 6 AM",
        "HTTP request checks certificate status via SSL checker API",
        "Condition checks if days remaining <= 14",
        "If expiring: sends email to DevOps and posts Slack warning",
      ],
      connections: [
        "SSL checker API (ssl-checker.example.com)",
        "SMTP server for email alerts",
        "Slack workspace for notifications",
      ],
      prerequisites: [
        "SSL certificate monitoring API access",
        "DevOps team email distribution list",
      ],
      similar: ["it-disk-space-alert", "it-incident-response"],
    },
  }),
  T({
    id: "it-disk-space-alert",
    name: "Disk Space Threshold Alert",
    description: "Routes disk alerts by severity level — critical to Slack, warnings via email",
    category: "IT Ops",
    subcategory: "Infrastructure Monitoring",
    nodes: [
      { type: "trigger", label: "Disk Metric", position: { x: 300, y: 0 } },
      { type: "switch", label: "Severity", position: { x: 300, y: 140 }, config: { value: "severity", rules: [{ value: "critical", output: 0 }, { value: "warning", output: 1 }] } },
      { type: "slack", label: "Critical Alert", position: { x: 100, y: 280 } },
      { type: "database", label: "Log Alert", position: { x: 100, y: 420 } },
      { type: "email", label: "Warning Email", position: { x: 500, y: 280 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2, sourceHandle: "case1" },
      { from: 1, to: 4, sourceHandle: "case2" },
      { from: 1, to: 3, sourceHandle: "default" },
      { from: 2, to: 3 },
    ],
    docs: {
      overview: "Receives disk metric alerts via webhook and routes by the severity field. critical goes to Slack and is logged, warning is emailed to the IT team, anything else falls through to the database log.",
      steps: [
        "Monitoring tool sends disk metrics to webhook (e.g. { severity: \"critical\", host: \"web-01\" })",
        "Switch node routes on the severity field",
        "critical: Critical alert to Slack + log to database",
        "warning: Warning email to IT team",
        "Any other value: falls through to the database log",
      ],
      connections: [
        "Server monitoring tool (Prometheus, Nagios)",
        "Slack channel for critical alerts",
        "SMTP for warning emails",
        "Database for alert logging",
      ],
      prerequisites: [
        "Server monitoring with disk metrics",
        "Slack workspace access",
      ],
      similar: ["it-incident-response", "it-db-failure-recovery"],
    },
  }),
  T({
    id: "it-deploy-rollback",
    name: "Deployment Rollback Trigger",
    description: "Auto-rolls back a deployment when error rate spikes above threshold",
    category: "IT Ops",
    subcategory: "Deployment Safety",
    nodes: [
      { type: "trigger", label: "Deploy Metrics", position: { x: 300, y: 0 } },
      { type: "condition", label: "Error Rate > 5%?", position: { x: 300, y: 140 } },
      { type: "http", label: "Trigger Rollback", position: { x: 150, y: 280 } },
      { type: "slack", label: "Notify Rollback", position: { x: 150, y: 420 } },
      { type: "database", label: "Log Stable", position: { x: 450, y: 280 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2, sourceHandle: "true" },
      { from: 1, to: 4, sourceHandle: "false" },
      { from: 2, to: 3 },
    ],
    docs: {
      overview: "Monitors deployment error rates via webhook. When error rate exceeds 5%, automatically triggers rollback via deployment API, notifies DevOps via Slack. If stable, logs the deployment as successful.",
      steps: [
        "Deployment tool sends metrics to webhook",
        "Condition checks if error rate > 5%",
        "If high: triggers rollback via HTTP API",
        "Sends Slack notification about rollback",
        "If stable: logs deployment as healthy",
      ],
      connections: [
        "Deployment platform API (Kubernetes, ECS, etc.)",
        "Slack channel for DevOps alerts",
        "Database for deployment logging",
      ],
      prerequisites: [
        "Deployment platform with rollback API",
        "Error rate monitoring in place",
      ],
      similar: ["it-incident-response", "devops-rollback-spike"],
    },
  }),
];

// ─── SECOPS ─────────────────────────────────────────────────────────────
const secOps: BuilderTemplate[] = [
  T({
    id: "sec-threat-detection",
    name: "Security Threat Detection",
    description: "Monitor logs for threats with AI analysis, block malicious IPs, send SOC alerts",
    category: "SecOps",
    subcategory: "Threat Detection",
    nodes: [
      { type: "trigger", label: "Log Ingestion", position: { x: 300, y: 0 } },
      { type: "code", label: "Parse Log Entry", position: { x: 300, y: 140 } },
      { type: "ai", label: "Threat Analysis", position: { x: 300, y: 280 } },
      { type: "condition", label: "Is Malicious?", position: { x: 300, y: 420 } },
      { type: "http", label: "Block IP via Firewall", position: { x: 150, y: 560 } },
      { type: "slack", label: "SOC Alert Channel", position: { x: 150, y: 700 } },
      { type: "email", label: "Incident Email", position: { x: 450, y: 560 } },
      { type: "database", label: "Store Threat Intel", position: { x: 300, y: 840 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
      { from: 3, to: 4, sourceHandle: "true" },
      { from: 3, to: 6, sourceHandle: "false" },
      { from: 4, to: 5 },
      { from: 5, to: 7 },
      { from: 6, to: 7 },
    ],
    docs: {
      overview: "Ingests security logs via webhook, parses entries with code, uses AI to analyze threat level. Malicious IPs are blocked via firewall API and SOC is alerted. Non-malicious events are emailed for review and all events are logged.",
      steps: [
        "Security logs (firewall, IDS) are sent to webhook",
        "Code node parses log structure",
        "AI analyzes the parsed entry for threat indicators",
        "If malicious: blocks IP via firewall API and alerts SOC on Slack",
        "If benign: sends incident email for review",
        "All events stored in threat intelligence database",
      ],
      connections: [
        "Firewall/IDS log sources",
        "Firewall API for IP blocking",
        "Slack SOC channel",
        "Threat intelligence database",
      ],
      prerequisites: [
        "Firewall with IP blocking API",
        "SOC Slack channel configured",
        "Threat intelligence DB schema",
      ],
      similar: ["sec-phishing-detection", "sec-malware-response"],
    },
  }),
  T({
    id: "sec-phishing-detection",
    name: "Phishing Email Detection",
    description: "AI screens inbound email for phishing indicators and quarantines threats",
    category: "SecOps",
    subcategory: "Email Security",
    nodes: [
      { type: "trigger", label: "Email Alert", position: { x: 300, y: 0 } },
      { type: "ai", label: "Detect Phishing", position: { x: 300, y: 140 } },
      { type: "condition", label: "Is Phishing?", position: { x: 300, y: 280 } },
      { type: "database", label: "Log Event", position: { x: 150, y: 420 } },
      { type: "slack", label: "Alert SOC", position: { x: 150, y: 560 } },
      { type: "auth", label: "Quarantine", position: { x: 150, y: 700 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3, sourceHandle: "true" },
      { from: 3, to: 4 },
      { from: 4, to: 5 },
    ],
    docs: {
      overview: "Receives email alerts via webhook and uses AI to detect phishing indicators. Phishing emails are logged, SOC is alerted, and the email is quarantined via mail gateway API.",
      steps: [
        "Email gateway sends inbound email to webhook",
        "AI analyzes email body for phishing patterns",
        "If phishing detected: logs security event",
        "Alerts SOC team on Slack",
        "Quarantines the email via mail gateway API",
      ],
      connections: [
        "Email gateway/webhook (SendGrid, Mailgun)",
        "AI provider (OpenAI GPT-4)",
        "Security event database",
        "Mail gateway quarantine API",
      ],
      prerequisites: [
        "Email gateway with webhook forwarding",
        "OpenAI API key",
        "Mail gateway API access",
      ],
      similar: ["sec-threat-detection", "sec-malware-response"],
    },
  }),
  T({
    id: "sec-malware-response",
    name: "Malware Detection Response",
    description: "Isolates infected hosts above a threat-level threshold and alerts SOC",
    category: "SecOps",
    subcategory: "Incident Response",
    nodes: [
      { type: "trigger", label: "AV Alert", position: { x: 300, y: 0 } },
      { type: "condition", label: "Threat Level >= 8?", position: { x: 300, y: 140 } },
      { type: "auth", label: "Isolate Host", position: { x: 150, y: 280 } },
      { type: "database", label: "Log Event", position: { x: 150, y: 420 } },
      { type: "slack", label: "Alert SOC", position: { x: 150, y: 560 } },
      { type: "email", label: "Notify Security", position: { x: 450, y: 280 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2, sourceHandle: "true" },
      { from: 1, to: 5, sourceHandle: "false" },
      { from: 2, to: 3 },
      { from: 3, to: 4 },
    ],
    docs: {
      overview: "Receives antivirus alerts via webhook. High-threat detections (level >= 8) trigger automatic host isolation, event logging, and SOC notification. Lower threats are emailed for review.",
      steps: [
        "AV tool sends alert to webhook",
        "Condition checks if threat level >= 8",
        "High threat: isolates host via EDR API",
        "Logs security event and alerts SOC on Slack",
        "Low threat: emails security team for review",
      ],
      connections: [
        "Antivirus/EDR tool (CrowdStrike, SentinelOne)",
        "EDR API for host isolation",
        "Security event database",
        "Slack SOC channel",
      ],
      prerequisites: [
        "EDR solution with host isolation API",
        "Security event logging table",
      ],
      similar: ["sec-threat-detection", "sec-data-exfiltration"],
    },
  }),
  T({
    id: "sec-api-anomaly",
    name: "Suspicious API Access Pattern",
    description: "AI flags anomalous API usage patterns for security review",
    category: "SecOps",
    subcategory: "Anomaly Detection",
    nodes: [
      { type: "trigger", label: "API Log", position: { x: 300, y: 0 } },
      { type: "ai", label: "Detect Anomaly", position: { x: 300, y: 140 } },
      { type: "condition", label: "Is Anomalous?", position: { x: 300, y: 280 } },
      { type: "database", label: "Log Anomaly", position: { x: 150, y: 420 } },
      { type: "slack", label: "Alert SOC", position: { x: 150, y: 560 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3, sourceHandle: "true" },
      { from: 3, to: 4 },
    ],
    docs: {
      overview: "Monitors API access logs via webhook, uses AI to detect anomalous patterns (unusual hours, high volume, unusual endpoints). Anomalies are logged and SOC is alerted.",
      steps: [
        "API gateway sends access logs to webhook",
        "AI analyzes the pattern for anomalies",
        "If anomalous: logs the anomaly with reason",
        "Alerts SOC on Slack with details",
      ],
      connections: [
        "API gateway log streaming",
        "AI provider (Anthropic Claude)",
        "Anomaly database table",
        "Slack SOC channel",
      ],
      prerequisites: [
        "API gateway with log streaming",
        "Anthropic API key",
      ],
      similar: ["sec-threat-detection", "sec-data-exfiltration"],
    },
  }),
  T({
    id: "sec-data-exfiltration",
    name: "Data Exfiltration Alert",
    description: "Blocks egress and alerts SOC on large outbound data transfers",
    category: "SecOps",
    subcategory: "Data Protection",
    nodes: [
      { type: "trigger", label: "DLP Alert", position: { x: 300, y: 0 } },
      { type: "condition", label: "Volume > 500MB?", position: { x: 300, y: 140 } },
      { type: "auth", label: "Block Egress", position: { x: 150, y: 280 } },
      { type: "database", label: "Log Event", position: { x: 150, y: 420 } },
      { type: "slack", label: "Alert SOC", position: { x: 150, y: 560 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2, sourceHandle: "true" },
      { from: 2, to: 3 },
      { from: 3, to: 4 },
    ],
    docs: {
      overview: "Monitors DLP (Data Loss Prevention) alerts. When outbound data transfer exceeds 500MB, blocks egress via proxy API, logs the event, and alerts SOC.",
      steps: [
        "DLP tool sends alert to webhook",
        "Condition checks if data volume > 500MB",
        "If exceeded: blocks egress via proxy/firewall API",
        "Logs the security event",
        "Alerts SOC on Slack",
      ],
      connections: [
        "DLP tool (Digital Guardian, Symantec DLP)",
        "Proxy/firewall API for egress blocking",
        "Security event database",
        "Slack SOC channel",
      ],
      prerequisites: [
        "DLP solution in place",
        "Proxy/firewall with blocking API",
      ],
      similar: ["sec-threat-detection", "sec-malware-response"],
    },
  }),
];

// ─── DEVOPS ─────────────────────────────────────────────────────────────
const devOps: BuilderTemplate[] = [
  T({
    id: "devops-ci-pipeline",
    name: "CI/CD Pipeline Monitor",
    description: "Monitor GitHub pushes, trigger builds, run tests, deploy on success, notify on failure",
    category: "DevOps",
    subcategory: "CI/CD Automation",
    nodes: [
      { type: "trigger", label: "GitHub Push Event", position: { x: 300, y: 0 } },
      { type: "http", label: "Trigger Jenkins Build", position: { x: 300, y: 140 } },
      { type: "code", label: "Parse Test Results", position: { x: 300, y: 280 } },
      { type: "condition", label: "Tests Passed?", position: { x: 300, y: 420 } },
      { type: "http", label: "Deploy to Staging", position: { x: 150, y: 560 } },
      { type: "slack", label: "Deploy Success", position: { x: 150, y: 700 } },
      { type: "slack", label: "Build Failed Alert", position: { x: 450, y: 560 } },
      { type: "database", label: "Audit Trail", position: { x: 300, y: 840 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
      { from: 3, to: 4, sourceHandle: "true" },
      { from: 3, to: 6, sourceHandle: "false" },
      { from: 4, to: 5 },
      { from: 5, to: 7 },
      { from: 6, to: 7 },
    ],
    docs: {
      overview: "Listens for GitHub push events, triggers Jenkins builds, parses test results. On success, deploys to staging and notifies Slack. On failure, sends build failure alerts. All actions are audit-logged.",
      steps: [
        "GitHub webhook sends push event",
        "Triggers Jenkins build via API",
        "Parses test results from build output",
        "If tests pass: deploys to staging and notifies Slack",
        "If tests fail: sends build failure alert to Slack",
        "All build/deploy events logged to audit trail",
      ],
      connections: [
        "GitHub repository webhook",
        "Jenkins API for build triggering",
        "Slack channel for deploy notifications",
        "Audit trail database",
      ],
      prerequisites: [
        "Jenkins server with API access",
        "GitHub webhook configured",
        "Staging environment deployment pipeline",
      ],
      similar: ["devops-deploy-tracker", "devops-container-health"],
    },
  }),
  T({
    id: "devops-deploy-tracker",
    name: "Deployment Success Tracker",
    description: "Logs successful deploys and notifies for production only",
    category: "DevOps",
    subcategory: "Deployment Tracking",
    nodes: [
      { type: "trigger", label: "Deploy Success", position: { x: 300, y: 0 } },
      { type: "database", label: "Log Deployment", position: { x: 300, y: 140 } },
      { type: "switch", label: "Is Production?", position: { x: 300, y: 280 } },
      { type: "slack", label: "Notify Prod Deploy", position: { x: 150, y: 420 } },
      { type: "set", label: "No-op Log", position: { x: 450, y: 420 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3, sourceHandle: "case1" },
      { from: 2, to: 4, sourceHandle: "default" },
    ],
    docs: {
      overview: "Tracks deployment success events. Logs all deployments to database, but only sends Slack notifications for production deployments.",
      steps: [
        "Deployment tool sends success webhook",
        "Logs deployment details (commit, env, status) to database",
        "Switch checks if environment is production",
        "Production: sends Slack notification",
        "Non-production: logs silently",
      ],
      connections: [
        "Deployment platform webhook",
        "Database for deployment logging",
        "Slack channel for production notifications",
      ],
      prerequisites: [
        "Deployment platform with webhook support",
        "Deployments table in database",
      ],
      similar: ["devops-ci-pipeline", "devops-rollback-spike"],
    },
  }),
  T({
    id: "devops-coverage-alert",
    name: "Test Coverage Drop Alert",
    description: "Flags PRs that drop test coverage below threshold",
    category: "DevOps",
    subcategory: "Code Quality",
    nodes: [
      { type: "trigger", label: "Coverage Report", position: { x: 300, y: 0 } },
      { type: "condition", label: "Coverage < 80%?", position: { x: 300, y: 140 } },
      { type: "slack", label: "Alert Team", position: { x: 150, y: 280 } },
      { type: "database", label: "Log History", position: { x: 300, y: 420 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2, sourceHandle: "true" },
      { from: 1, to: 3, sourceHandle: "false" },
      { from: 2, to: 3 },
    ],
    docs: {
      overview: "Monitors test coverage reports. When coverage drops below 80%, alerts the team on Slack. All coverage results are logged for historical tracking.",
      steps: [
        "CI/CD pipeline sends coverage report to webhook",
        "Condition checks if coverage < 80%",
        "If low: alerts team on Slack",
        "All results logged to coverage history table",
      ],
      connections: [
        "CI/CD pipeline (GitHub Actions, Jenkins)",
        "Slack channel for quality alerts",
        "Coverage history database table",
      ],
      prerequisites: [
        "Test coverage reporting in CI pipeline",
        "Coverage history table schema",
      ],
      similar: ["devops-ci-pipeline", "devops-container-health"],
    },
  }),
  T({
    id: "devops-container-health",
    name: "Container Health Check",
    description: "Polls health endpoint every 5 min, restarts on failure",
    category: "DevOps",
    subcategory: "Infrastructure Monitoring",
    nodes: [
      { type: "trigger", label: "Every 5 Min", position: { x: 300, y: 0 }, config: { triggerType: "cron", cronExpression: "*/5 * * * *" } },
      { type: "http", label: "Health Check", position: { x: 300, y: 140 } },
      { type: "condition", label: "Not 200?", position: { x: 300, y: 280 } },
      { type: "http", label: "Restart Container", position: { x: 150, y: 420 } },
      { type: "slack", label: "Notify Restart", position: { x: 150, y: 560 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3, sourceHandle: "true" },
      { from: 3, to: 4 },
    ],
    docs: {
      overview: "Polls container health endpoints every 5 minutes. If health check returns non-200 status, automatically restarts the container via orchestrator API and notifies the team.",
      steps: [
        "Cron trigger fires every 5 minutes",
        "HTTP request to health check endpoint",
        "Condition checks if status != 200",
        "If unhealthy: restarts container via orchestrator API",
        "Notifies team on Slack about the restart",
      ],
      connections: [
        "Container orchestrator (Docker, K8s)",
        "Health check endpoints",
        "Slack notification channel",
      ],
      prerequisites: [
        "Container orchestrator with restart API",
        "Health check endpoints configured",
      ],
      similar: ["devops-ci-pipeline", "devops-rollback-spike"],
    },
  }),
  T({
    id: "devops-rollback-spike",
    name: "Rollback on Error-Rate Spike",
    description: "Double-checks sustained error spikes before rolling back",
    category: "DevOps",
    subcategory: "Deployment Safety",
    nodes: [
      { type: "trigger", label: "Error Metric", position: { x: 300, y: 0 } },
      { type: "condition", label: "Error Rate > 10%?", position: { x: 300, y: 140 } },
      { type: "delay", label: "Wait 2 Min", position: { x: 150, y: 280 }, config: { delayType: "fixed", duration: 2, unit: "minutes" } },
      { type: "http", label: "Recheck Metrics", position: { x: 150, y: 420 } },
      { type: "condition", label: "Still High?", position: { x: 150, y: 560 } },
      { type: "http", label: "Rollback", position: { x: 50, y: 700 } },
      { type: "slack", label: "Notify", position: { x: 50, y: 840 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2, sourceHandle: "true" },
      { from: 2, to: 3 },
      { from: 3, to: 4 },
      { from: 4, to: 5, sourceHandle: "true" },
      { from: 5, to: 6 },
    ],
    docs: {
      overview: "Monitors error rate metrics. When error rate exceeds 10%, waits 2 minutes and rechecks to confirm it's sustained (not a spike). If still high, triggers rollback and notifies the team.",
      steps: [
        "Monitoring sends error metrics to webhook",
        "Checks if error rate > 10%",
        "If high: waits 2 minutes for confirmation",
        "Rechecks metrics after delay",
        "If still high: triggers rollback via deploy API",
        "Notifies team on Slack",
      ],
      connections: [
        "Monitoring tool (Datadog, Prometheus)",
        "Deployment API for rollback",
        "Slack notification channel",
      ],
      prerequisites: [
        "Deployment platform with rollback capability",
        "Error rate monitoring",
      ],
      similar: ["devops-ci-pipeline", "it-deploy-rollback"],
    },
  }),
];

// ─── SALES ──────────────────────────────────────────────────────────────
const sales: BuilderTemplate[] = [
  T({
    id: "sales-lead-qualification",
    name: "Sales Lead Qualification",
    description: "Capture leads from forms, enrich with AI scoring, route hot leads to CRM, nurture cold leads",
    category: "Sales",
    subcategory: "Lead Management",
    nodes: [
      { type: "trigger", label: "New Lead Form", position: { x: 300, y: 0 } },
      { type: "set", label: "Enrich Lead Data", position: { x: 300, y: 140 } },
      { type: "ai", label: "AI Lead Scoring", position: { x: 300, y: 280 } },
      { type: "condition", label: "Score > 80?", position: { x: 300, y: 420 } },
      { type: "http", label: "Create CRM Deal", position: { x: 150, y: 560 } },
      { type: "slack", label: "Sales Alert", position: { x: 150, y: 700 } },
      { type: "email", label: "Nurture Sequence", position: { x: 450, y: 560 } },
      { type: "database", label: "Log Scoring", position: { x: 300, y: 840 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
      { from: 3, to: 4, sourceHandle: "true" },
      { from: 3, to: 6, sourceHandle: "false" },
      { from: 4, to: 5 },
      { from: 5, to: 7 },
      { from: 6, to: 7 },
    ],
    docs: {
      overview: "Captures leads from form submissions, enriches with company data, uses AI to score lead quality. Hot leads (score > 80) are pushed to CRM and sales is alerted. Cold leads receive nurture email sequences.",
      steps: [
        "Lead form submits to webhook",
        "Enriches lead with company data",
        "AI scores the lead based on fit and intent",
        "Score > 80: creates CRM deal and alerts sales on Slack",
        "Score <= 80: enrolls in nurture email sequence",
        "All scoring results logged to database",
      ],
      connections: [
        "Lead capture form/webhook",
        "CRM API (Salesforce, HubSpot)",
        "Email marketing platform",
        "AI scoring provider",
      ],
      prerequisites: [
        "CRM with API access",
        "Email marketing platform",
        "Lead enrichment data source",
      ],
      similar: ["sales-demo-routing", "sales-renewal-risk"],
    },
  }),
  T({
    id: "sales-demo-routing",
    name: "Demo Request Routing",
    description: "Routes demo requests to enterprise or general sales based on existing account",
    category: "Sales",
    subcategory: "Lead Management",
    nodes: [
      { type: "trigger", label: "Demo Requested", position: { x: 300, y: 0 } },
      { type: "database", label: "Lookup Account", position: { x: 300, y: 140 } },
      { type: "condition", label: "Existing Account?", position: { x: 300, y: 280 } },
      { type: "slack", label: "Enterprise Sales", position: { x: 150, y: 420 } },
      { type: "slack", label: "General Sales", position: { x: 450, y: 420 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3, sourceHandle: "true" },
      { from: 2, to: 4, sourceHandle: "false" },
    ],
    docs: {
      overview: "Receives demo requests via webhook, looks up the company in the database. Existing accounts are routed to enterprise sales; new accounts go to general sales.",
      steps: [
        "Demo request form submits to webhook",
        "Looks up company in accounts database",
        "If existing account: routes to enterprise sales Slack",
        "If new account: routes to general sales Slack",
      ],
      connections: [
        "Demo request form/webhook",
        "Accounts database",
        "Enterprise sales Slack channel",
        "General sales Slack channel",
      ],
      prerequisites: [
        "CRM/accounts database with company records",
        "Slack channels for sales teams",
      ],
      similar: ["sales-lead-qualification", "sales-cold-outreach"],
    },
  }),
  T({
    id: "sales-cold-outreach",
    name: "Cold Outreach Reply Classification",
    description: "Classifies email replies and routes hot leads instantly",
    category: "Sales",
    subcategory: "Outreach Automation",
    nodes: [
      { type: "trigger", label: "Email Reply", position: { x: 300, y: 0 } },
      { type: "ai", label: "Classify Reply", position: { x: 300, y: 140 } },
      { type: "switch", label: "Route", position: { x: 300, y: 280 } },
      { type: "slack", label: "Hot Reply", position: { x: 100, y: 420 } },
      { type: "database", label: "Unsubscribe", position: { x: 500, y: 420 } },
      { type: "set", label: "Follow Up Later", position: { x: 300, y: 560 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3, sourceHandle: "case1" },
      { from: 2, to: 4, sourceHandle: "case2" },
      { from: 2, to: 5, sourceHandle: "default" },
    ],
    docs: {
      overview: "Receives email replies to cold outreach campaigns. AI classifies replies as interested, not interested, out of office, or unsubscribe. Hot replies go to sales Slack; unsubscribes are processed; others are flagged for follow-up.",
      steps: [
        "Email reply triggers webhook",
        "AI classifies the reply intent",
        "Switch routes by classification",
        "Interested: alerts sales on Slack",
        "Unsubscribe: updates contact in database",
        "Other: flags for later follow-up",
      ],
      connections: [
        "Email platform webhook (SendGrid, Mailgun)",
        "AI provider for classification",
        "Slack sales channel",
        "Contacts database",
      ],
      prerequisites: [
        "Cold outreach email sequences set up",
        "AI classification API key",
      ],
      similar: ["sales-lead-qualification", "sales-renewal-risk"],
    },
  }),
  T({
    id: "sales-renewal-risk",
    name: "Renewal Risk Detection",
    description: "Weekly scan of upcoming renewals for churn risk",
    category: "Sales",
    subcategory: "Customer Success",
    nodes: [
      { type: "trigger", label: "Weekly Scan", position: { x: 300, y: 0 }, config: { triggerType: "cron", cronExpression: "0 8 * * 1" } },
      { type: "database", label: "Find Upcoming Renewals", position: { x: 300, y: 140 } },
      { type: "ai", label: "Assess Risk", position: { x: 300, y: 280 } },
      { type: "condition", label: "High Risk?", position: { x: 300, y: 420 } },
      { type: "slack", label: "Alert CS", position: { x: 150, y: 560 } },
      { type: "email", label: "Notify CSM", position: { x: 150, y: 700 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
      { from: 3, to: 4, sourceHandle: "true" },
      { from: 4, to: 5 },
    ],
    docs: {
      overview: "Runs weekly to scan accounts with renewals within 30 days. AI assesses churn risk based on usage, support tickets, and engagement. High-risk accounts trigger Slack alerts and CSM email notifications.",
      steps: [
        "Cron triggers weekly on Monday at 8 AM",
        "Finds accounts with renewals in next 30 days",
        "AI assesses churn risk for each account",
        "If high risk: alerts CS team on Slack",
        "Sends detailed email to account CSM",
      ],
      connections: [
        "Accounts database",
        "AI provider for risk assessment",
        "Slack customer success channel",
        "SMTP for CSM notifications",
      ],
      prerequisites: [
        "Accounts table with renewal dates",
        "Customer success Slack channel",
      ],
      similar: ["sales-lead-qualification", "support-vip-escalation"],
    },
  }),
  T({
    id: "sales-webinar-followup",
    name: "Event/Webinar Lead Follow-up",
    description: "Sends delayed thank-you and logs webinar attendee as a lead",
    category: "Sales",
    subcategory: "Event Automation",
    nodes: [
      { type: "trigger", label: "Attendee Recorded", position: { x: 300, y: 0 } },
      { type: "delay", label: "Wait 1 Hour", position: { x: 300, y: 140 }, config: { delayType: "fixed", duration: 1, unit: "hours" } },
      { type: "email", label: "Thank You Email", position: { x: 300, y: 280 } },
      { type: "database", label: "Create Lead", position: { x: 300, y: 420 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
    ],
    docs: {
      overview: "When a webinar attendee is recorded, waits 1 hour then sends a thank-you email and logs the attendee as a lead in the database.",
      steps: [
        "Webinar platform sends attendee to webhook",
        "Waits 1 hour before follow-up",
        "Sends personalized thank-you email",
        "Creates lead record in database",
      ],
      connections: [
        "Webinar platform (Zoom, Demio)",
        "Email service for thank-you",
        "Leads database table",
      ],
      prerequisites: [
        "Webinar platform with webhook support",
        "Leads table schema",
      ],
      similar: ["sales-lead-qualification", "sales-demo-routing"],
    },
  }),
];

// ─── HR ─────────────────────────────────────────────────────────────────
const hr: BuilderTemplate[] = [
  T({
    id: "hr-resume-screening",
    name: "HR Resume Screening",
    description: "Parse incoming resumes with AI, extract skills, score candidates against job requirements",
    category: "HR",
    subcategory: "Recruitment",
    nodes: [
      { type: "trigger", label: "Job Application", position: { x: 300, y: 0 } },
      { type: "ai", label: "Extract Skills", position: { x: 300, y: 140 } },
      { type: "ai", label: "Score Candidate", position: { x: 300, y: 280 } },
      { type: "condition", label: "Qualified?", position: { x: 300, y: 420 } },
      { type: "database", label: "Add to Shortlist", position: { x: 150, y: 560 } },
      { type: "slack", label: "Recruiter Alert", position: { x: 150, y: 700 } },
      { type: "email", label: "Rejection Email", position: { x: 450, y: 560 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
      { from: 3, to: 4, sourceHandle: "true" },
      { from: 3, to: 6, sourceHandle: "false" },
      { from: 4, to: 5 },
    ],
    docs: {
      overview: "Receives job applications via webhook, uses AI to extract skills from resumes, scores candidates against job requirements. Qualified candidates are shortlisted and recruiters are alerted. Unqualified candidates receive rejection emails.",
      steps: [
        "Job application submitted to webhook",
        "AI extracts skills and experience from resume",
        "AI scores candidate against job requirements",
        "If qualified: adds to shortlist and alerts recruiter",
        "If not qualified: sends polite rejection email",
      ],
      connections: [
        "Job application form/webhook",
        "AI provider for skill extraction",
        "Candidates database",
        "Slack recruiter channel",
        "SMTP for rejection emails",
      ],
      prerequisites: [
        "Job requirements document for scoring criteria",
        "AI API key",
        "Candidates table schema",
      ],
      similar: ["hr-interview-scheduling", "hr-onboarding-checklist"],
    },
  }),
  T({
    id: "hr-interview-scheduling",
    name: "Interview Scheduling Automation",
    description: "Auto-books an interview slot once a candidate is approved",
    category: "HR",
    subcategory: "Recruitment",
    nodes: [
      { type: "trigger", label: "Candidate Approved", position: { x: 300, y: 0 } },
      { type: "http", label: "Book Slot", position: { x: 300, y: 140 } },
      { type: "email", label: "Confirm to Candidate", position: { x: 300, y: 280 } },
      { type: "slack", label: "Notify HR", position: { x: 300, y: 420 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
    ],
    docs: {
      overview: "When a candidate is approved, automatically books an interview slot via calendar API, sends confirmation email to candidate, and notifies HR on Slack.",
      steps: [
        "HR approves candidate via webhook",
        "Books interview slot via calendar API",
        "Sends confirmation email to candidate",
        "Notifies HR team on Slack",
      ],
      connections: [
        "Calendar API (Google Calendar, Calendly)",
        "SMTP for candidate emails",
        "Slack HR channel",
      ],
      prerequisites: [
        "Calendar API access",
        "HR Slack channel",
      ],
      similar: ["hr-resume-screening", "hr-onboarding-checklist"],
    },
  }),
  T({
    id: "hr-onboarding-checklist",
    name: "Onboarding Checklist Trigger",
    description: "Kicks off provisioning and welcome tasks for a new hire",
    category: "HR",
    subcategory: "Employee Lifecycle",
    nodes: [
      { type: "trigger", label: "New Hire", position: { x: 300, y: 0 } },
      { type: "database", label: "Create Checklist", position: { x: 300, y: 140 } },
      { type: "email", label: "Request IT Provisioning", position: { x: 150, y: 280 } },
      { type: "email", label: "Welcome Email", position: { x: 450, y: 280 } },
      { type: "slack", label: "Notify HR", position: { x: 300, y: 420 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 1, to: 3 },
      { from: 2, to: 4 },
      { from: 3, to: 4 },
    ],
    docs: {
      overview: "When a new hire is recorded, creates onboarding checklist, requests IT provisioning via email, sends welcome email, and notifies HR on Slack.",
      steps: [
        "New hire data submitted to webhook",
        "Creates onboarding task checklist in database",
        "Sends IT provisioning request email",
        "Sends welcome email to new hire",
        "Notifies HR team on Slack",
      ],
      connections: [
        "HR system webhook",
        "IT team email for provisioning",
        "SMTP for welcome email",
        "Slack HR onboarding channel",
      ],
      prerequisites: [
        "Onboarding tasks table schema",
        "IT provisioning email template",
      ],
      similar: ["hr-offboarding", "hr-interview-scheduling"],
    },
  }),
  T({
    id: "hr-offboarding",
    name: "Offboarding Workflow",
    description: "Revokes access and logs completion when an employee exits",
    category: "HR",
    subcategory: "Employee Lifecycle",
    nodes: [
      { type: "trigger", label: "Employee Exit", position: { x: 300, y: 0 } },
      { type: "auth", label: "Revoke Access", position: { x: 300, y: 140 } },
      { type: "database", label: "Update Status", position: { x: 300, y: 280 } },
      { type: "slack", label: "Notify IT Security", position: { x: 150, y: 420 } },
      { type: "email", label: "Confirm to HR", position: { x: 450, y: 420 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
      { from: 2, to: 4 },
    ],
    docs: {
      overview: "When an employee exit is triggered, revokes system access via identity API, updates employee status in database, notifies IT security on Slack, and sends confirmation to HR.",
      steps: [
        "Employee exit event triggers webhook",
        "Revokes access via identity provider API",
        "Updates employee status to 'offboarded'",
        "Notifies IT security on Slack",
        "Sends confirmation email to HR",
      ],
      connections: [
        "Identity provider API (Okta, Azure AD)",
        "Employees database table",
        "Slack IT security channel",
        "SMTP for HR confirmation",
      ],
      prerequisites: [
        "Identity provider with access revocation API",
        "Employee status tracking table",
      ],
      similar: ["hr-onboarding-checklist", "hr-reference-check"],
    },
  }),
  T({
    id: "hr-reference-check",
    name: "Reference Check Automation",
    description: "Requests, waits for, and summarizes a candidate reference",
    category: "HR",
    subcategory: "Recruitment",
    nodes: [
      { type: "trigger", label: "Reference Requested", position: { x: 300, y: 0 } },
      { type: "email", label: "Request Reference", position: { x: 300, y: 140 } },
      { type: "delay", label: "Wait for Response", position: { x: 300, y: 280 }, config: { delayType: "fixed", duration: 1, unit: "days" } },
      { type: "ai", label: "Summarize Sentiment", position: { x: 300, y: 420 } },
      { type: "database", label: "Save Summary", position: { x: 300, y: 560 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
      { from: 3, to: 4 },
    ],
    docs: {
      overview: "Sends reference check request email, waits for response, uses AI to summarize sentiment, and saves the summary to the candidate record.",
      steps: [
        "Reference request triggers webhook",
        "Sends reference check email to referee",
        "Waits for response (configurable delay)",
        "AI summarizes the reference sentiment",
        "Saves summary to candidate record in database",
      ],
      connections: [
        "SMTP for reference request emails",
        "AI provider for sentiment analysis",
        "Candidates database table",
      ],
      prerequisites: [
        "Reference check email template",
        "AI API key",
      ],
      similar: ["hr-resume-screening", "hr-interview-scheduling"],
    },
  }),
];

// ─── E-COMMERCE ─────────────────────────────────────────────────────────
const ecommerce: BuilderTemplate[] = [
  T({
    id: "ecom-order-processing",
    name: "E-Commerce Order Processing",
    description: "Process new orders, verify payment, check inventory, handle shipping, send confirmation",
    category: "E-Commerce",
    subcategory: "Order Management",
    nodes: [
      { type: "trigger", label: "New Order", position: { x: 300, y: 0 } },
      { type: "http", label: "Verify Payment", position: { x: 300, y: 140 } },
      { type: "condition", label: "Payment OK?", position: { x: 300, y: 280 } },
      { type: "database", label: "Check Inventory", position: { x: 150, y: 420 } },
      { type: "condition", label: "In Stock?", position: { x: 150, y: 560 } },
      { type: "http", label: "Create Shipment", position: { x: 50, y: 700 } },
      { type: "email", label: "Shipping Confirmation", position: { x: 50, y: 840 } },
      { type: "email", label: "Out of Stock Notice", position: { x: 250, y: 700 } },
      { type: "email", label: "Payment Failed", position: { x: 450, y: 420 } },
      { type: "database", label: "Update Order Status", position: { x: 150, y: 980 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3, sourceHandle: "true" },
      { from: 2, to: 8, sourceHandle: "false" },
      { from: 3, to: 4 },
      { from: 4, to: 5, sourceHandle: "true" },
      { from: 4, to: 7, sourceHandle: "false" },
      { from: 5, to: 6 },
      { from: 6, to: 9 },
      { from: 7, to: 9 },
    ],
    docs: {
      overview: "End-to-end order processing: verifies payment, checks inventory, creates shipment if in stock, sends confirmation emails, handles out-of-stock and payment failure cases.",
      steps: [
        "New order submitted via webhook",
        "Verifies payment via payment gateway API",
        "If payment fails: sends payment failed email",
        "If payment OK: checks inventory in database",
        "If in stock: creates shipment and sends shipping confirmation",
        "If out of stock: sends out of stock notice",
        "Updates order status in database",
      ],
      connections: [
        "Payment gateway (Stripe, PayPal)",
        "Inventory database",
        "Shipping API (ShipStation, EasyPost)",
        "SMTP for order emails",
      ],
      prerequisites: [
        "Payment gateway API credentials",
        "Inventory management system",
        "Shipping API access",
      ],
      similar: ["ecom-cart-recovery", "ecom-fraud-detection"],
    },
  }),
  T({
    id: "ecom-cart-recovery",
    name: "Abandoned Cart Recovery",
    description: "Sends a recovery email if a cart isn't converted within 2 hours",
    category: "E-Commerce",
    subcategory: "Conversion Optimization",
    nodes: [
      { type: "trigger", label: "Cart Abandoned", position: { x: 300, y: 0 } },
      { type: "delay", label: "Wait 2 Hours", position: { x: 300, y: 140 }, config: { delayType: "fixed", duration: 2, unit: "hours" } },
      { type: "database", label: "Check Completion", position: { x: 300, y: 280 } },
      { type: "condition", label: "Still Abandoned?", position: { x: 300, y: 420 } },
      { type: "email", label: "Recovery Email", position: { x: 300, y: 560 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
      { from: 3, to: 4, sourceHandle: "true" },
    ],
    docs: {
      overview: "When a cart is abandoned, waits 2 hours then checks if the order was completed. If still abandoned, sends a recovery email with cart contents.",
      steps: [
        "Cart abandonment detected via webhook",
        "Waits 2 hours before follow-up",
        "Checks if order was completed in database",
        "If still abandoned: sends recovery email",
      ],
      connections: [
        "E-commerce platform webhook",
        "Orders database",
        "Email service for recovery emails",
      ],
      prerequisites: [
        "Cart abandonment tracking",
        "Recovery email template",
      ],
      similar: ["ecom-order-processing", "ecom-inventory-alert"],
    },
  }),
  T({
    id: "ecom-inventory-alert",
    name: "Inventory Low-Stock Alert",
    description: "Flags low stock and notifies procurement",
    category: "E-Commerce",
    subcategory: "Inventory Management",
    nodes: [
      { type: "trigger", label: "Inventory Update", position: { x: 300, y: 0 } },
      { type: "condition", label: "Stock <= 10?", position: { x: 300, y: 140 } },
      { type: "database", label: "Flag Low Stock", position: { x: 150, y: 280 } },
      { type: "slack", label: "Alert Inventory Team", position: { x: 150, y: 420 } },
      { type: "email", label: "Notify Procurement", position: { x: 150, y: 560 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2, sourceHandle: "true" },
      { from: 2, to: 3 },
      { from: 3, to: 4 },
    ],
    docs: {
      overview: "Monitors inventory updates. When stock drops to 10 or below, flags the product as low stock, alerts the inventory team on Slack, and notifies procurement via email.",
      steps: [
        "Inventory system sends update to webhook",
        "Checks if stock level <= 10",
        "If low: flags product as low stock in database",
        "Alerts inventory team on Slack",
        "Sends reorder notification to procurement",
      ],
      connections: [
        "Inventory management system",
        "Products database table",
        "Slack inventory channel",
        "SMTP for procurement emails",
      ],
      prerequisites: [
        "Inventory tracking system with webhooks",
        "Low stock threshold configured",
      ],
      similar: ["ecom-order-processing", "ecom-fraud-detection"],
    },
  }),
  T({
    id: "ecom-return-refund",
    name: "Return/Refund Processing",
    description: "AI checks return policy compliance before auto-refunding",
    category: "E-Commerce",
    subcategory: "Order Management",
    nodes: [
      { type: "trigger", label: "Return Requested", position: { x: 300, y: 0 } },
      { type: "ai", label: "Check Policy", position: { x: 300, y: 140 } },
      { type: "condition", label: "Approved?", position: { x: 300, y: 280 } },
      { type: "http", label: "Process Refund", position: { x: 150, y: 420 } },
      { type: "email", label: "Refund Confirmed", position: { x: 150, y: 560 } },
      { type: "email", label: "Needs Review", position: { x: 450, y: 420 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3, sourceHandle: "true" },
      { from: 2, to: 5, sourceHandle: "false" },
      { from: 3, to: 4 },
    ],
    docs: {
      overview: "Receives return requests, uses AI to check policy compliance. Approved returns are auto-refunded via payment API and customer is notified. Non-compliant returns are flagged for manual review.",
      steps: [
        "Return request submitted to webhook",
        "AI checks if return is within policy",
        "If approved: processes refund via payment API",
        "Sends refund confirmation email",
        "If not approved: sends needs-review email",
      ],
      connections: [
        "Payment gateway for refunds (Stripe, PayPal)",
        "AI provider for policy checking",
        "SMTP for customer emails",
      ],
      prerequisites: [
        "Return policy documentation for AI context",
        "Payment gateway refund API",
      ],
      similar: ["ecom-order-processing", "ecom-fraud-detection"],
    },
  }),
  T({
    id: "ecom-fraud-detection",
    name: "Fraud Order Detection",
    description: "AI risk-scores new orders and holds high-risk ones for review",
    category: "E-Commerce",
    subcategory: "Security",
    nodes: [
      { type: "trigger", label: "New Order", position: { x: 300, y: 0 } },
      { type: "ai", label: "Score Fraud Risk", position: { x: 300, y: 140 } },
      { type: "condition", label: "Risk >= 75?", position: { x: 300, y: 280 } },
      { type: "database", label: "Hold Order", position: { x: 150, y: 420 } },
      { type: "slack", label: "Alert Fraud Team", position: { x: 150, y: 560 } },
      { type: "database", label: "Confirm Order", position: { x: 450, y: 420 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3, sourceHandle: "true" },
      { from: 2, to: 5, sourceHandle: "false" },
      { from: 3, to: 4 },
    ],
    docs: {
      overview: "Receives new orders via webhook, uses AI to score fraud risk (0-100). High-risk orders (>=75) are held for review and fraud team is alerted. Low-risk orders are confirmed automatically.",
      steps: [
        "New order submitted to webhook",
        "AI scores fraud risk based on order details",
        "If risk >= 75: holds order and alerts fraud team",
        "If risk < 75: confirms order automatically",
      ],
      connections: [
        "E-commerce platform webhook",
        "AI provider for fraud scoring",
        "Orders database",
        "Slack fraud review channel",
      ],
      prerequisites: [
        "AI fraud scoring prompt/context",
        "Fraud review Slack channel",
      ],
      similar: ["ecom-order-processing", "ecom-return-refund"],
    },
  }),
];

// ─── FINANCE ────────────────────────────────────────────────────────────
const finance: BuilderTemplate[] = [
  T({
    id: "finance-invoice-processing",
    name: "Finance Invoice Processing",
    description: "Extract invoice data with AI, validate amounts, detect anomalies, approve or escalate",
    category: "Finance",
    subcategory: "Accounts Payable",
    nodes: [
      { type: "trigger", label: "Invoice Received", position: { x: 300, y: 0 } },
      { type: "ai", label: "Extract Invoice Data", position: { x: 300, y: 140 } },
      { type: "code", label: "Validate Amounts", position: { x: 300, y: 280 } },
      { type: "condition", label: "Amount > $10K?", position: { x: 300, y: 420 } },
      { type: "slack", label: "Finance Team Alert", position: { x: 150, y: 560 } },
      { type: "database", label: "Pending Approval", position: { x: 150, y: 700 } },
      { type: "database", label: "Auto-Approve", position: { x: 450, y: 560 } },
      { type: "email", label: "Approval Confirmation", position: { x: 450, y: 700 } },
      { type: "database", label: "Log to Ledger", position: { x: 300, y: 840 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
      { from: 3, to: 4, sourceHandle: "true" },
      { from: 3, to: 6, sourceHandle: "false" },
      { from: 4, to: 5 },
      { from: 6, to: 7 },
      { from: 5, to: 8 },
      { from: 7, to: 8 },
    ],
    docs: {
      overview: "Processes incoming invoices: extracts data with AI, validates amounts with code, routes high-value invoices (>$10K) to finance team for approval, auto-approves smaller ones, and logs everything to the ledger.",
      steps: [
        "Invoice submitted via webhook",
        "AI extracts invoice data (vendor, amount, items)",
        "Code node validates amounts and detects anomalies",
        "If amount > $10K: alerts finance team and creates pending approval",
        "If amount <= $10K: auto-approves and sends confirmation",
        "All invoices logged to ledger",
      ],
      connections: [
        "Invoice submission webhook",
        "AI provider for data extraction",
        "Finance approval workflow",
        "Ledger database",
      ],
      prerequisites: [
        "AI invoice extraction prompt",
        "Ledger table schema",
        "Finance team Slack channel",
      ],
      similar: ["finance-expense-approval", "finance-duplicate-detection"],
    },
  }),
  T({
    id: "finance-expense-approval",
    name: "Expense Report Auto-Approval",
    description: "Auto-approves small expenses, routes larger ones to manager review",
    category: "Finance",
    subcategory: "Expense Management",
    nodes: [
      { type: "trigger", label: "Expense Submitted", position: { x: 300, y: 0 } },
      { type: "condition", label: "Amount <= $200?", position: { x: 300, y: 140 } },
      { type: "database", label: "Auto-Approve", position: { x: 150, y: 280 } },
      { type: "email", label: "Notify Employee", position: { x: 150, y: 420 } },
      { type: "slack", label: "Manager Review Needed", position: { x: 450, y: 280 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2, sourceHandle: "true" },
      { from: 1, to: 4, sourceHandle: "false" },
      { from: 2, to: 3 },
    ],
    docs: {
      overview: "Receives expense reports via webhook. Expenses under $200 are auto-approved and the employee is notified. Larger expenses are routed to managers for review.",
      steps: [
        "Expense report submitted to webhook",
        "Checks if amount <= $200",
        "If small: auto-approves and notifies employee",
        "If large: routes to manager via Slack",
      ],
      connections: [
        "Expense submission webhook",
        "Expenses database",
        "SMTP for employee notifications",
        "Slack for manager alerts",
      ],
      prerequisites: [
        "Expense approval threshold configured",
        "Manager Slack channel",
      ],
      similar: ["finance-invoice-processing", "finance-duplicate-detection"],
    },
  }),
  T({
    id: "finance-duplicate-detection",
    name: "Duplicate Invoice Detection",
    description: "Checks for matching vendor+amount before recording a new invoice",
    category: "Finance",
    subcategory: "Accounts Payable",
    nodes: [
      { type: "trigger", label: "Invoice Submitted", position: { x: 300, y: 0 } },
      { type: "database", label: "Check Existing", position: { x: 300, y: 140 } },
      { type: "condition", label: "Duplicate Found?", position: { x: 300, y: 280 } },
      { type: "slack", label: "Flag Duplicate", position: { x: 150, y: 420 } },
      { type: "database", label: "Record Invoice", position: { x: 450, y: 420 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3, sourceHandle: "true" },
      { from: 2, to: 4, sourceHandle: "false" },
    ],
    docs: {
      overview: "When an invoice is submitted, checks for existing invoices with the same vendor and amount. Duplicates are flagged on Slack; unique invoices are recorded to the database.",
      steps: [
        "Invoice submitted to webhook",
        "Queries database for matching vendor+amount",
        "If duplicate found: flags on Slack for review",
        "If unique: records invoice in database",
      ],
      connections: [
        "Invoice submission webhook",
        "Invoices database",
        "Slack finance alerts channel",
      ],
      prerequisites: [
        "Invoices table with vendor/amount fields",
      ],
      similar: ["finance-invoice-processing", "finance-expense-approval"],
    },
  }),
  T({
    id: "finance-vendor-reminder",
    name: "Vendor Payment Reminder",
    description: "Daily batch reminder emails for invoices due soon",
    category: "Finance",
    subcategory: "Accounts Payable",
    nodes: [
      { type: "trigger", label: "Daily Check", position: { x: 300, y: 0 }, config: { triggerType: "cron", cronExpression: "0 7 * * *" } },
      { type: "database", label: "Find Due Invoices", position: { x: 300, y: 140 } },
      { type: "loop", label: "Loop Invoices", position: { x: 300, y: 280 } },
      { type: "email", label: "Send Reminder", position: { x: 300, y: 420 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3, sourceHandle: "done" },
    ],
    docs: {
      overview: "Runs daily to find invoices due within 3 days. Loops through each invoice and sends payment reminder emails to vendors.",
      steps: [
        "Cron trigger fires daily at 7 AM",
        "Finds unpaid invoices due within 3 days",
        "Loops through each invoice",
        "Sends payment reminder email to vendor",
      ],
      connections: [
        "Invoices database",
        "SMTP for vendor emails",
      ],
      prerequisites: [
        "Invoices table with due dates",
        "Vendor email addresses in invoice records",
      ],
      similar: ["finance-invoice-processing", "finance-budget-alert"],
    },
  }),
  T({
    id: "finance-budget-alert",
    name: "Budget Threshold Alert",
    description: "Alerts finance leads when department spend crosses 90%",
    category: "Finance",
    subcategory: "Budget Management",
    nodes: [
      { type: "trigger", label: "Spend Update", position: { x: 300, y: 0 } },
      { type: "condition", label: "Spent >= 90%?", position: { x: 300, y: 140 } },
      { type: "slack", label: "Alert Finance", position: { x: 150, y: 280 } },
      { type: "email", label: "Notify Leads", position: { x: 150, y: 420 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2, sourceHandle: "true" },
      { from: 2, to: 3 },
    ],
    docs: {
      overview: "Monitors department spend updates. When spend reaches 90% of budget, alerts finance team on Slack and sends email to department leads.",
      steps: [
        "Finance system sends spend update to webhook",
        "Checks if spent percentage >= 90%",
        "If threshold reached: alerts finance on Slack",
        "Sends email notification to department leads",
      ],
      connections: [
        "Finance/budgeting system webhook",
        "Slack finance alerts channel",
        "SMTP for lead notifications",
      ],
      prerequisites: [
        "Budget tracking system with webhooks",
        "Department lead email addresses",
      ],
      similar: ["finance-expense-approval", "finance-duplicate-detection"],
    },
  }),
];

// ─── SUPPORT ────────────────────────────────────────────────────────────
const support: BuilderTemplate[] = [
  T({
    id: "support-ticket-routing",
    name: "Customer Support Routing",
    description: "Receive support tickets, AI categorizes urgency and topic, routes to right team, generates draft response",
    category: "Support",
    subcategory: "Ticket Management",
    nodes: [
      { type: "trigger", label: "Support Ticket", position: { x: 300, y: 0 } },
      { type: "ai", label: "Categorize Ticket", position: { x: 300, y: 140 } },
      { type: "ai", label: "Generate Response", position: { x: 300, y: 280 } },
      { type: "condition", label: "Is Urgent?", position: { x: 300, y: 420 } },
      { type: "slack", label: "Urgent Support Channel", position: { x: 150, y: 560 } },
      { type: "database", label: "Priority Queue", position: { x: 150, y: 700 } },
      { type: "email", label: "Customer Acknowledgment", position: { x: 450, y: 560 } },
      { type: "database", label: "Standard Queue", position: { x: 450, y: 700 } },
      { type: "database", label: "Track Resolution", position: { x: 300, y: 840 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
      { from: 3, to: 4, sourceHandle: "true" },
      { from: 3, to: 6, sourceHandle: "false" },
      { from: 4, to: 5 },
      { from: 6, to: 7 },
      { from: 5, to: 8 },
      { from: 7, to: 8 },
    ],
    docs: {
      overview: "Receives support tickets via webhook, uses AI to categorize urgency and topic, generates draft response. Urgent tickets go to priority channel; standard tickets get acknowledgment email. All tracked for resolution.",
      steps: [
        "Support ticket submitted to webhook",
        "AI categorizes urgency and topic",
        "AI generates draft response",
        "If urgent: routes to priority Slack channel",
        "If standard: sends acknowledgment email to customer",
        "All tickets logged and tracked for resolution",
      ],
      connections: [
        "Support system webhook (Zendesk, Freshdesk)",
        "AI provider for categorization",
        "Slack support channels",
        "Tickets database",
      ],
      prerequisites: [
        "Support ticket schema",
        "AI categorization prompt",
        "Slack support channels configured",
      ],
      similar: ["support-vip-escalation", "support-sla-breach"],
    },
  }),
  T({
    id: "support-vip-escalation",
    name: "VIP Customer Escalation",
    description: "Routes VIP tickets to a priority channel",
    category: "Support",
    subcategory: "Customer Segmentation",
    nodes: [
      { type: "trigger", label: "New Ticket", position: { x: 300, y: 0 } },
      { type: "database", label: "Lookup Customer", position: { x: 300, y: 140 } },
      { type: "condition", label: "Is VIP?", position: { x: 300, y: 280 } },
      { type: "slack", label: "VIP Channel", position: { x: 150, y: 420 } },
      { type: "database", label: "Standard Queue", position: { x: 450, y: 420 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3, sourceHandle: "true" },
      { from: 2, to: 4, sourceHandle: "false" },
    ],
    docs: {
      overview: "Receives support tickets, looks up customer tier in database. VIP customers are routed to a priority Slack channel; standard customers go to the regular queue.",
      steps: [
        "Ticket submitted to webhook",
        "Looks up customer in database",
        "If VIP: routes to VIP Slack channel",
        "If standard: creates ticket in standard queue",
      ],
      connections: [
        "Support system webhook",
        "Customers database with tier field",
        "Slack VIP support channel",
        "Tickets database",
      ],
      prerequisites: [
        "Customer tier data in database",
        "VIP support Slack channel",
      ],
      similar: ["support-ticket-routing", "support-sla-breach"],
    },
  }),
  T({
    id: "support-sla-breach",
    name: "SLA Breach Alert",
    description: "Periodic check for tickets that have breached SLA",
    category: "Support",
    subcategory: "SLA Management",
    nodes: [
      { type: "trigger", label: "Every 15 Min", position: { x: 300, y: 0 }, config: { triggerType: "cron", cronExpression: "*/15 * * * *" } },
      { type: "database", label: "Find Breached", position: { x: 300, y: 140 } },
      { type: "condition", label: "Any Breaches?", position: { x: 300, y: 280 } },
      { type: "slack", label: "Alert Management", position: { x: 300, y: 420 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3, sourceHandle: "true" },
    ],
    docs: {
      overview: "Checks every 15 minutes for tickets that have breached SLA. If any breaches are found, alerts support management on Slack.",
      steps: [
        "Cron trigger fires every 15 minutes",
        "Queries for open tickets with SLA breached",
        "If any found: alerts management on Slack",
      ],
      connections: [
        "Tickets database",
        "Slack management channel",
      ],
      prerequisites: [
        "SLA tracking in ticket system",
        "Management Slack channel",
      ],
      similar: ["support-ticket-routing", "support-bug-routing"],
    },
  }),
  T({
    id: "support-bug-routing",
    name: "Bug Report to Dev Team Routing",
    description: "AI identifies bug reports and routes to the correct dev channel",
    category: "Support",
    subcategory: "Ticket Management",
    nodes: [
      { type: "trigger", label: "New Ticket", position: { x: 300, y: 0 } },
      { type: "ai", label: "Classify Bug", position: { x: 300, y: 140 } },
      { type: "condition", label: "Is Bug?", position: { x: 300, y: 280 } },
      { type: "switch", label: "Route by Team", position: { x: 150, y: 420 }, config: { value: "team", rules: [{ value: "frontend", output: 0 }, { value: "backend", output: 1 }] } },
      { type: "slack", label: "Frontend Channel", position: { x: 50, y: 560 } },
      { type: "slack", label: "Backend Channel", position: { x: 150, y: 560 } },
      { type: "database", label: "General Ticket", position: { x: 450, y: 420 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3, sourceHandle: "true" },
      { from: 2, to: 6, sourceHandle: "false" },
      { from: 3, to: 4, sourceHandle: "case1" },
      { from: 3, to: 5, sourceHandle: "case2" },
      { from: 3, to: 6, sourceHandle: "default" },
    ],
    docs: {
      overview: "Receives support tickets, uses AI to identify bug reports and classify by team (frontend/backend). Bug reports are routed to the correct dev channel; anything else (non-bugs or unrecognised teams) goes to the general queue.",
      steps: [
        "Ticket submitted to webhook",
        "AI classifies if it's a bug and which team",
        "If bug: routes to frontend/backend channel",
        "If not bug, or team is not frontend/backend: creates general ticket",
      ],
      connections: [
        "Support system webhook",
        "AI provider for classification",
        "Slack dev channels",
        "Tickets database",
      ],
      prerequisites: [
        "Dev team Slack channels",
        "AI classification prompt",
      ],
      similar: ["support-ticket-routing", "support-nps-collection"],
    },
  }),
  T({
    id: "support-nps-collection",
    name: "Feedback/NPS Collection",
    description: "Flags detractor NPS scores for CS follow-up and logs all responses",
    category: "Support",
    subcategory: "Customer Feedback",
    nodes: [
      { type: "trigger", label: "NPS Response", position: { x: 300, y: 0 } },
      { type: "condition", label: "Score <= 6?", position: { x: 300, y: 140 } },
      { type: "slack", label: "Alert CS", position: { x: 150, y: 280 } },
      { type: "database", label: "Log Response", position: { x: 300, y: 420 } },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2, sourceHandle: "true" },
      { from: 1, to: 3, sourceHandle: "false" },
      { from: 2, to: 3 },
    ],
    docs: {
      overview: "Receives NPS survey responses. Detractor scores (<=6) alert the customer success team on Slack. All responses are logged to the database.",
      steps: [
        "NPS survey platform sends response to webhook",
        "Checks if score <= 6 (detractor)",
        "If detractor: alerts CS team on Slack",
        "All responses logged to database",
      ],
      connections: [
        "NPS survey platform (Typeform, SurveyMonkey)",
        "Slack customer success channel",
        "NPS responses database",
      ],
      prerequisites: [
        "NPS survey with webhook integration",
        "CS Slack channel",
      ],
      similar: ["support-ticket-routing", "support-vip-escalation"],
    },
  }),
];

// ─── EXPORTS ────────────────────────────────────────────────────────────
export const allTemplates: BuilderTemplate[] = [
  ...itOps, ...secOps, ...devOps, ...sales,
  ...hr, ...ecommerce, ...finance, ...support,
];

export const categories = [
  "All", "IT Ops", "SecOps", "DevOps", "Sales",
  "HR", "E-Commerce", "Finance", "Support",
];

export const subcategories: Record<string, string[]> = {
  "IT Ops": ["Incident Response", "Infrastructure Monitoring", "Security Monitoring", "Deployment Safety"],
  "SecOps": ["Threat Detection", "Email Security", "Incident Response", "Anomaly Detection", "Data Protection"],
  "DevOps": ["CI/CD Automation", "Deployment Tracking", "Code Quality", "Infrastructure Monitoring", "Deployment Safety"],
  "Sales": ["Lead Management", "Outreach Automation", "Customer Success", "Event Automation"],
  "HR": ["Recruitment", "Employee Lifecycle"],
  "E-Commerce": ["Order Management", "Conversion Optimization", "Inventory Management", "Security"],
  "Finance": ["Accounts Payable", "Expense Management", "Budget Management"],
  "Support": ["Ticket Management", "Customer Segmentation", "SLA Management", "Customer Feedback"],
};
